<?= $this->extend('layouts/base') ?>

<?= $this->section('stylesheet') ?>
<?= $this->endSection() ?>

<?= $this->section('content') ?>
<div class="container-fluid site-slider-container">
	<h1>Precision Farming Solutions</h1>
	<div class="slide" style="background-image: url('https://images.unsplash.com/photo-1496181133206-80ce9b88a853?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1351&q=80')"></div>
	
	<div class="slide" style="background-image: url('https://images.unsplash.com/photo-1453928582365-b6ad33cbcf64?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1352&q=80')"></div>
	
	<div class="slide" style="background-image: url('https://images.unsplash.com/photo-1504707748692-419802cf939d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1330&q=80')"></div>
	
	<div class="controls-container">
		<div class="control"></div>
		<div class="control"></div>
		<div class="control"></div>
	</div>
</div>
<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque tincidunt, risus nec cursus tempor, dolor nisl auctor ante, vel tincidunt velit neque ac dolor. Etiam eget tellus at nisl semper auctor tincidunt at diam. Nam id nibh sed justo tristique tempus. In ac condimentum sapien. Phasellus rutrum convallis urna non commodo. Integer euismod bibendum erat quis fringilla. Ut et purus dolor. Maecenas viverra maximus magna, quis placerat dui auctor fringilla.

Cras efficitur urna enim, sed convallis tortor consequat euismod. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aenean laoreet at mi id interdum. Sed aliquam sapien ut placerat condimentum. Phasellus orci dolor, aliquet nec ex quis, auctor posuere metus. Aenean gravida posuere nisi, luctus faucibus tellus porta a. Sed gravida odio velit, vitae fringilla arcu lacinia vitae. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi interdum ultrices consequat. Aliquam sagittis eros vel felis convallis tristique. Proin ut dui nec eros tempus euismod. Proin dictum eleifend arcu sed malesuada.

Donec aliquet pulvinar consequat. Aenean sed tellus at metus pretium bibendum non a sapien. Nullam vulputate ornare lectus, et laoreet libero blandit sit amet. Integer vehicula tellus in orci vulputate feugiat. Quisque ligula purus, porta in ipsum sed, elementum euismod diam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed et nisi nibh. Duis consectetur sapien non leo pretium, ut faucibus est fringilla. Nam facilisis justo ac posuere tincidunt.

Maecenas malesuada vitae nunc ac ornare. Aenean orci lorem, luctus eu auctor id, luctus sit amet ante. Fusce condimentum quam vitae ligula congue, sit amet aliquam neque scelerisque. Proin ut blandit mi. Phasellus iaculis diam sed semper sollicitudin. Donec rhoncus elementum nisi, sed hendrerit quam dignissim vel. Donec elementum magna sit amet mi tincidunt, vel facilisis neque mattis. Praesent lobortis sed dui non finibus. Proin sit amet sollicitudin justo, quis consectetur felis. Duis at ornare enim. Morbi commodo tempus scelerisque. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Nullam luctus, odio vitae interdum dapibus, eros dui cursus dui, in pretium est sem facilisis tellus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent vel sollicitudin est. Aenean quis interdum massa. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam id justo eu tellus ultricies vehicula. Ut ultricies est vel facilisis commodo. Vivamus ut mi risus. Pellentesque rutrum ultricies ex, eget sodales nisi dignissim quis. Pellentesque lorem sem, venenatis congue sem et, placerat ornare purus. Proin suscipit semper pellentesque.

Vestibulum congue convallis fringilla. Ut vel purus dignissim, gravida metus vitae, volutpat odio. Morbi ultricies sem mauris, eu varius neque lacinia vel. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Morbi tempor pellentesque nulla eu hendrerit. Praesent rhoncus, velit ac tempor interdum, risus enim blandit metus, et feugiat dolor magna sit amet orci. Sed id neque ut ex ultrices commodo.

Curabitur id ex neque. Morbi mollis felis at magna placerat, ac finibus erat bibendum. Suspendisse tortor ipsum, posuere vitae tempor a, rhoncus non risus. Donec laoreet varius tortor quis finibus. Sed a sodales libero. Donec rutrum sem et ligula rutrum, sed commodo sapien vulputate. Vestibulum eget purus at nisi congue congue sit amet eu enim. Vivamus vitae nibh eget dolor porttitor dapibus sed pellentesque orci.

Vivamus semper, nulla eget congue blandit, nulla tortor feugiat erat, et sagittis felis nisl ac eros. Curabitur sollicitudin sagittis vestibulum. Aliquam in risus non ipsum tempor laoreet. Vivamus tempor vehicula libero et tristique. Aenean volutpat libero quis lorem commodo tristique. Maecenas convallis dolor feugiat, tempor ipsum eu, ornare mauris. Etiam consectetur mollis pharetra.

Duis sed ornare eros. Suspendisse non purus vel orci ultrices molestie. Mauris mollis, arcu ut auctor venenatis, erat velit aliquam justo, in dapibus massa augue nec ante. Aenean at orci pretium diam viverra venenatis ac sodales quam. Donec vel tortor ut enim luctus vehicula. Nam at nunc sit amet ligula aliquam scelerisque. Praesent sit amet sapien et nisl tincidunt ultrices vitae in felis. Aenean quis fringilla lectus. Morbi tortor turpis, ultricies vitae semper at, semper ut ante. Pellentesque nec viverra purus. Sed euismod libero est. Donec consectetur nunc vitae ex molestie aliquet. Proin auctor sapien in egestas volutpat. Duis sodales lorem ac nulla suscipit imperdiet. Duis varius ante at felis viverra dictum. Suspendisse interdum facilisis tincidunt.

Sed interdum lectus dapibus hendrerit consectetur. In convallis sapien ut convallis maximus. Quisque imperdiet sodales ultrices. Fusce laoreet lacus sit amet mattis feugiat. Nam eget pretium est, vel suscipit libero. Proin ultrices sem in est tristique malesuada. Maecenas a risus lobortis, aliquet enim vel, posuere risus. Proin scelerisque eu massa in porttitor. Duis scelerisque, arcu sit amet aliquam maximus, diam metus eleifend ante, eget cursus tellus nibh bibendum massa.

Maecenas non maximus lacus. Quisque interdum ornare malesuada. Cras sit amet urna et lorem aliquet porttitor. Suspendisse porttitor erat et placerat tempor. Nulla a magna sit amet massa consequat eleifend id facilisis neque. Phasellus et scelerisque nibh. Nunc ac ligula pretium lectus lacinia blandit nec id metus. Phasellus vel congue sem. Sed non aliquam erat, vel venenatis augue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas diam ipsum, auctor a suscipit quis, aliquet et magna. Praesent arcu ex, molestie non ornare viverra, porta sodales est. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id egestas lacus.

Integer id elit non purus vulputate volutpat eu cursus lacus. Donec gravida convallis quam, eu convallis elit pharetra nec. In nec fringilla odio, nec efficitur nulla. Fusce purus nunc, auctor sit amet iaculis ut, hendrerit vel erat. Quisque iaculis in ex sit amet aliquam. Pellentesque faucibus in erat non porttitor. Vivamus vel nunc imperdiet nisi elementum pretium. Nullam felis lorem, pretium a tellus nec, bibendum dignissim arcu.

Etiam blandit finibus eros, a maximus magna blandit nec. Vivamus pellentesque commodo nisi, at eleifend lorem vulputate id. Nulla egestas consectetur leo, id fringilla quam aliquet a. Sed sit amet imperdiet quam, sit amet viverra massa. Aliquam aliquet consequat purus quis vestibulum. Praesent lectus neque, posuere eu aliquet eu, efficitur vitae lectus. Donec aliquet tellus nulla, in finibus sem condimentum non. Etiam erat ipsum, aliquet nec tellus vitae, mattis mattis dui. Sed sit amet leo in odio mattis egestas eget sed quam. Nulla felis erat, tempor a commodo eu, fermentum vitae turpis. Quisque et dui non nisi cursus ultricies. Nam accumsan odio metus, tincidunt pulvinar ligula placerat pretium. Pellentesque sagittis sem at libero hendrerit, in dictum leo convallis. Praesent nunc risus, sodales at auctor molestie, viverra at odio.

Etiam tincidunt bibendum ipsum maximus luctus. Fusce tincidunt felis id mi accumsan, id porta felis tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin pretium, felis a lobortis iaculis, sapien neque dignissim tellus, id faucibus purus velit vel turpis. Maecenas non luctus lorem. Quisque volutpat enim nisi, facilisis gravida mauris aliquam sit amet. Duis pellentesque nunc sit amet ipsum interdum, eget vestibulum turpis dictum. Sed ut viverra ipsum. Sed vitae ex in mauris luctus rhoncus vitae a est. Integer ornare condimentum ligula a imperdiet. Vivamus vulputate libero in urna ullamcorper bibendum. In porta auctor arcu sed dictum. Donec lacinia elit odio, pharetra luctus lacus imperdiet convallis. Integer condimentum dolor ligula. Nam id sem quis ex fermentum sagittis quis eu mi.

Aliquam tellus enim, pharetra sed neque a, dictum bibendum magna. Duis vel justo quam. Aliquam elementum eleifend lacus. Phasellus sit amet finibus est. Duis vehicula pulvinar turpis ut posuere. Phasellus tincidunt nunc vitae gravida molestie. Suspendisse vitae vestibulum metus, vitae efficitur enim. Aenean in nulla sit amet libero vestibulum sodales at quis nisl. Pellentesque varius, augue vitae euismod dapibus, augue lorem egestas odio, eu dictum felis ipsum vel ligula. Nulla facilisi. Praesent ac pulvinar nunc. Donec mauris ipsum, lacinia a porta ac, rhoncus ut turpis. Quisque nisl ex, facilisis sed maximus tincidunt, gravida at dolor. Vivamus sodales diam id nunc tempor, vel faucibus orci pharetra. Vivamus in justo semper lorem euismod interdum vel at nisi.
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque tincidunt, risus nec cursus tempor, dolor nisl auctor ante, vel tincidunt velit neque ac dolor. Etiam eget tellus at nisl semper auctor tincidunt at diam. Nam id nibh sed justo tristique tempus. In ac condimentum sapien. Phasellus rutrum convallis urna non commodo. Integer euismod bibendum erat quis fringilla. Ut et purus dolor. Maecenas viverra maximus magna, quis placerat dui auctor fringilla.

Cras efficitur urna enim, sed convallis tortor consequat euismod. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Aenean laoreet at mi id interdum. Sed aliquam sapien ut placerat condimentum. Phasellus orci dolor, aliquet nec ex quis, auctor posuere metus. Aenean gravida posuere nisi, luctus faucibus tellus porta a. Sed gravida odio velit, vitae fringilla arcu lacinia vitae. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi interdum ultrices consequat. Aliquam sagittis eros vel felis convallis tristique. Proin ut dui nec eros tempus euismod. Proin dictum eleifend arcu sed malesuada.

Donec aliquet pulvinar consequat. Aenean sed tellus at metus pretium bibendum non a sapien. Nullam vulputate ornare lectus, et laoreet libero blandit sit amet. Integer vehicula tellus in orci vulputate feugiat. Quisque ligula purus, porta in ipsum sed, elementum euismod diam. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed et nisi nibh. Duis consectetur sapien non leo pretium, ut faucibus est fringilla. Nam facilisis justo ac posuere tincidunt.

Maecenas malesuada vitae nunc ac ornare. Aenean orci lorem, luctus eu auctor id, luctus sit amet ante. Fusce condimentum quam vitae ligula congue, sit amet aliquam neque scelerisque. Proin ut blandit mi. Phasellus iaculis diam sed semper sollicitudin. Donec rhoncus elementum nisi, sed hendrerit quam dignissim vel. Donec elementum magna sit amet mi tincidunt, vel facilisis neque mattis. Praesent lobortis sed dui non finibus. Proin sit amet sollicitudin justo, quis consectetur felis. Duis at ornare enim. Morbi commodo tempus scelerisque. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Nullam luctus, odio vitae interdum dapibus, eros dui cursus dui, in pretium est sem facilisis tellus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Praesent vel sollicitudin est. Aenean quis interdum massa. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam id justo eu tellus ultricies vehicula. Ut ultricies est vel facilisis commodo. Vivamus ut mi risus. Pellentesque rutrum ultricies ex, eget sodales nisi dignissim quis. Pellentesque lorem sem, venenatis congue sem et, placerat ornare purus. Proin suscipit semper pellentesque.

Vestibulum congue convallis fringilla. Ut vel purus dignissim, gravida metus vitae, volutpat odio. Morbi ultricies sem mauris, eu varius neque lacinia vel. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Morbi tempor pellentesque nulla eu hendrerit. Praesent rhoncus, velit ac tempor interdum, risus enim blandit metus, et feugiat dolor magna sit amet orci. Sed id neque ut ex ultrices commodo.

Curabitur id ex neque. Morbi mollis felis at magna placerat, ac finibus erat bibendum. Suspendisse tortor ipsum, posuere vitae tempor a, rhoncus non risus. Donec laoreet varius tortor quis finibus. Sed a sodales libero. Donec rutrum sem et ligula rutrum, sed commodo sapien vulputate. Vestibulum eget purus at nisi congue congue sit amet eu enim. Vivamus vitae nibh eget dolor porttitor dapibus sed pellentesque orci.

Vivamus semper, nulla eget congue blandit, nulla tortor feugiat erat, et sagittis felis nisl ac eros. Curabitur sollicitudin sagittis vestibulum. Aliquam in risus non ipsum tempor laoreet. Vivamus tempor vehicula libero et tristique. Aenean volutpat libero quis lorem commodo tristique. Maecenas convallis dolor feugiat, tempor ipsum eu, ornare mauris. Etiam consectetur mollis pharetra.

Duis sed ornare eros. Suspendisse non purus vel orci ultrices molestie. Mauris mollis, arcu ut auctor venenatis, erat velit aliquam justo, in dapibus massa augue nec ante. Aenean at orci pretium diam viverra venenatis ac sodales quam. Donec vel tortor ut enim luctus vehicula. Nam at nunc sit amet ligula aliquam scelerisque. Praesent sit amet sapien et nisl tincidunt ultrices vitae in felis. Aenean quis fringilla lectus. Morbi tortor turpis, ultricies vitae semper at, semper ut ante. Pellentesque nec viverra purus. Sed euismod libero est. Donec consectetur nunc vitae ex molestie aliquet. Proin auctor sapien in egestas volutpat. Duis sodales lorem ac nulla suscipit imperdiet. Duis varius ante at felis viverra dictum. Suspendisse interdum facilisis tincidunt.

Sed interdum lectus dapibus hendrerit consectetur. In convallis sapien ut convallis maximus. Quisque imperdiet sodales ultrices. Fusce laoreet lacus sit amet mattis feugiat. Nam eget pretium est, vel suscipit libero. Proin ultrices sem in est tristique malesuada. Maecenas a risus lobortis, aliquet enim vel, posuere risus. Proin scelerisque eu massa in porttitor. Duis scelerisque, arcu sit amet aliquam maximus, diam metus eleifend ante, eget cursus tellus nibh bibendum massa.

Maecenas non maximus lacus. Quisque interdum ornare malesuada. Cras sit amet urna et lorem aliquet porttitor. Suspendisse porttitor erat et placerat tempor. Nulla a magna sit amet massa consequat eleifend id facilisis neque. Phasellus et scelerisque nibh. Nunc ac ligula pretium lectus lacinia blandit nec id metus. Phasellus vel congue sem. Sed non aliquam erat, vel venenatis augue. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Maecenas diam ipsum, auctor a suscipit quis, aliquet et magna. Praesent arcu ex, molestie non ornare viverra, porta sodales est. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id egestas lacus.

Integer id elit non purus vulputate volutpat eu cursus lacus. Donec gravida convallis quam, eu convallis elit pharetra nec. In nec fringilla odio, nec efficitur nulla. Fusce purus nunc, auctor sit amet iaculis ut, hendrerit vel erat. Quisque iaculis in ex sit amet aliquam. Pellentesque faucibus in erat non porttitor. Vivamus vel nunc imperdiet nisi elementum pretium. Nullam felis lorem, pretium a tellus nec, bibendum dignissim arcu.

Etiam blandit finibus eros, a maximus magna blandit nec. Vivamus pellentesque commodo nisi, at eleifend lorem vulputate id. Nulla egestas consectetur leo, id fringilla quam aliquet a. Sed sit amet imperdiet quam, sit amet viverra massa. Aliquam aliquet consequat purus quis vestibulum. Praesent lectus neque, posuere eu aliquet eu, efficitur vitae lectus. Donec aliquet tellus nulla, in finibus sem condimentum non. Etiam erat ipsum, aliquet nec tellus vitae, mattis mattis dui. Sed sit amet leo in odio mattis egestas eget sed quam. Nulla felis erat, tempor a commodo eu, fermentum vitae turpis. Quisque et dui non nisi cursus ultricies. Nam accumsan odio metus, tincidunt pulvinar ligula placerat pretium. Pellentesque sagittis sem at libero hendrerit, in dictum leo convallis. Praesent nunc risus, sodales at auctor molestie, viverra at odio.

Etiam tincidunt bibendum ipsum maximus luctus. Fusce tincidunt felis id mi accumsan, id porta felis tincidunt. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin pretium, felis a lobortis iaculis, sapien neque dignissim tellus, id faucibus purus velit vel turpis. Maecenas non luctus lorem. Quisque volutpat enim nisi, facilisis gravida mauris aliquam sit amet. Duis pellentesque nunc sit amet ipsum interdum, eget vestibulum turpis dictum. Sed ut viverra ipsum. Sed vitae ex in mauris luctus rhoncus vitae a est. Integer ornare condimentum ligula a imperdiet. Vivamus vulputate libero in urna ullamcorper bibendum. In porta auctor arcu sed dictum. Donec lacinia elit odio, pharetra luctus lacus imperdiet convallis. Integer condimentum dolor ligula. Nam id sem quis ex fermentum sagittis quis eu mi.

Aliquam tellus enim, pharetra sed neque a, dictum bibendum magna. Duis vel justo quam. Aliquam elementum eleifend lacus. Phasellus sit amet finibus est. Duis vehicula pulvinar turpis ut posuere. Phasellus tincidunt nunc vitae gravida molestie. Suspendisse vitae vestibulum metus, vitae efficitur enim. Aenean in nulla sit amet libero vestibulum sodales at quis nisl. Pellentesque varius, augue vitae euismod dapibus, augue lorem egestas odio, eu dictum felis ipsum vel ligula. Nulla facilisi. Praesent ac pulvinar nunc. Donec mauris ipsum, lacinia a porta ac, rhoncus ut turpis. Quisque nisl ex, facilisis sed maximus tincidunt, gravida at dolor. Vivamus sodales diam id nunc tempor, vel faucibus orci pharetra. Vivamus in justo semper lorem euismod interdum vel at nisi.
</p>
<?= $this->endSection() ?>

<?= $this->section('javascript') ?>

<?= $this->endSection() ?>